[package]
edition.workspace = true
license.workspace = true
name              = "agent-launcher-runner"
version.workspace = true

[dependencies]
agent-launcher-core    = { path = "../core" }
async-trait.workspace  = true
chrono.workspace       = true
dirs.workspace         = true
futures-util.workspace = true
reqwest.workspace      = true
serde.workspace        = true
serde_json.workspace   = true
thiserror.workspace    = true
tokio.workspace        = true
tracing.workspace      = true
url                    = { features = ["serde"], workspace = true }
uuid                   = { features = ["v5"], workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { features = ["fs", "process"], version = "1" }
