[package]
name = "agent-launcher-runner"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
agent-launcher-core = { path = "../core" }
async-trait.workspace = true
chrono.workspace = true
dirs.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v5"] }
