[package]
name = "agent-launcher-tui"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
agent-launcher-core = { path = "../core" }
agent-launcher-runtime = { path = "../runtime" }
chrono.workspace = true
crossterm.workspace = true
futures-util.workspace = true
fuzzy-matcher.workspace = true
ratatui = { workspace = true, features = ["unstable-rendered-line-info"] }
serde_json.workspace = true
sysinfo.workspace = true
thiserror.workspace = true
tokio.workspace = true
